### PR TITLE
Use python3-numpy in mouse_teleop pkg.

### PR DESCRIPTION
**Pull request by hidmic**
Precisely what the title says. Required on Foxy. Perhaps this patch should go into a separate branch.

### CODE REVIEW

**Comment by hidmic** [comment]
CC @clalancette

**Comment by clalancette** [comment]
> Precisely what the title says. Required on Foxy. Perhaps this patch should go into a separate branch.

I don't think so; that was always broken.  I guess we never noticed before, but that should have been python3-numpy on Eloquent as well.  I'm going to approve, but I'd like to get @IanTheEngineer's opinion before merging.

**Review by clalancette — APPROVED** [review]

**Comment by hidmic** [comment]
@IanTheEngineer friendly ping.

**Comment by IanTheEngineer** [comment]
While I agree with the change, shouldn't it just be upstreamed to https://github.com/ros-teleop/teleop_tools/tree/foxy-devel ?

**Comment by clalancette** [comment]
> While I agree with the change, shouldn't it just be upstreamed to https://github.com/ros-teleop/teleop_tools/tree/foxy-devel ?

Yeah, that's a good point.  I'd suggest we move forward with merging this one, but also open a PR to the upstream to fix it there.

**Review by IanTheEngineer — APPROVED** [review]
Fine to merge here, but could you propagate the change upstream as well?

**Pull request merged**
